### ISSUE TITLE
Unable to train due to missing data

### ISSUE THREAD

**Issue by mekanix** [AidaDSP/aidadsp-lv2#46]
The log I got is
```
args.model = SimpleRNN
args.device = MOD-DWARF
args.file_name = neural
args.input_size = 1
args.hidden_size = 16
args.unit_type = LSTM
args.loss_fcns = {'ESR': 0.75, 'DC': 0.25}
args.skip_con = 0
args.pre_filt = A-Weighting
existing model file found, loading network.. continuing training..
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
  0% 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/dist_model_recnet.py", line 229, in <module>
    epoch_loss = network.train_epoch(dataset.subsets['train'].data['input'][0],
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 770, in train_epoch
    return ep_loss / (batch_i + 1)
UnboundLocalError: local variable 'batch_i' referenced before assignment

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-11-156e4608184f>](https://localhost:8080/#) in <cell line: 46>()
     44 model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"
     45 step = max(step, 2)
---> 46 print("Training done!\nESR after training: ", extract_best_esr_model(model_dir)[1])

[/content/Automated-GuitarAmpModelling/colab_functions.py](https://localhost:8080/#) in extract_best_esr_model(dirpath)
    159 def extract_best_esr_model(dirpath):
    160   stats_file = dirpath + "/training_stats.json"
--> 161   with open(stats_file) as json_file:
    162     stats_data = json.load(json_file)
    163     test_lossESR_final = stats_data['test_lossESR_final']

FileNotFoundError: [Errno 2] No such file or directory: '/content/Automated-GuitarAmpModelling/Results/neural_LSTM-16-0/training_stats.json'
```

**Comment by MaxPayne86** [comment]
See https://github.com/AidaDSP/Automated-GuitarAmpModelling/issues/8, closing
